language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: "pluto-atom-4-github"

jdk: openjdk10

script:
  - mvn clean verify
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
